### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by it19862** [sharomank/regex-tester#10]
_This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\VsixUpdater.1.0.28\build\VsixUpdater.targets.	RegexTester	Z:\vs\csharp\prb\531\01_pr\fl\RegexTester\RegexTester.csproj	346	
Ошибка		Не удалось добавить ссылку. Пакет "StreamJsonRpc" пытался добавить ссылку на платформу для объекта "System.Net.Http", который не найден в глобальном кэше сборок (GAC). Возможно, произошла ошибка в пакете. Обратитесь к владельцам пакета для получения помощи.
В результате вызова компонента COM возвращена ошибка в формате HRESULT E_FAIL.			0_	

![2018-10-29_11-40-58](https://user-images.githubusercontent.com/18245828/47638411-8be9ac80-db6f-11e8-83f9-98d58071f04c.png)

**Comment by sharomank** [comment]
I think this is outdated issue, please use latest version.
